---
- hosts: web_nodes
  become: yes
  vars:
    wordpress_url: https://pl.wordpress.org/wordpress-4.9.8-pl_PL.tar.gz
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    metric_store_ip: 172.31.23.183
  tasks:
    - name: "Apache server"
      yum:
        name: httpd
        state: latest
    - name: "Install php"
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - php
        - php-mysql
    - name : "Wordpress"
      get_url:
        url: https://pl.wordpress.org/wordpress-4.9.8-pl_PL.tar.gz
        dest: ~/wordpress.tar.gz
    - name: "unarchive wordpress archive"
      unarchive:
        src: ~/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
    - name: "Configure vhost"
      copy:
        src: template/vhosts.conf
        dest: /etc/httpd/conf.d/wordpress.conf
    - name: "Copy wordpress config to destination"
      copy:
       src: template/wp-config.php
       dest: /var/www/wordpress
    - name: "Start Serv"
      service:
        name: httpd
        state: restarted
    # Create Telegraf
    - name: "Install telegraf"
      yum:
        name: "{{telegraf_url}}"
        state: present
    - name: "copy cfg info est"
      template:
        src: template/telegraf.conf
        dest: /etc/telegraf/telegraf.conf
    - name: "start telegraf"
      service:
        name: "telegraf"
        state: restarted

- hosts: db_nodes
  become: yes
  tasks:
    - name: "Install db server"
      yum:
        name: "{{item}}"
      with_items:
        - mariadb
        - mariadb-server
    - service:
        name: mariadb
        state: started
    - name: "Install python dependencies"
      yum:
        name: MySQL-python
        state: present
    - name: "Start service mariadb, if not started"
      service:
        name: mariadb
        state: started
    - name: "Set Database"
      mysql_db:
        name: db_base
        state: present
    # Create database user with name 'bob' and password '12345' with all database privileges
    - name: "Create User"
      mysql_user:
        name: bob
        password: 12345
        priv: '*.*:ALL,GRANT'
        host: "%"
        state: present

- hosts: stats_nodes
  become: yes
  vars:
    influx_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
    grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
  tasks:
    - name: "Install influx"
      yum:
        name: "{{influx_url}}"
        state: present
    - service:
        name: influxdb
        state: started
    - name: "Install grafana"
      yum:
        name: "{{grafana_url}}"
        state: present
    - name: "Copy Grafana configuration"
      template:
        src: ./templates/grafana.ini
        dest: /etc/grafana/grafana.ini
    - name: "Create datasource for Grafana"
      grafana_datasource:
        name: "influxdb"
        grafana_url: "https://127.0.0.1:8080"
        grafana_user: "admin"
        grafana_password: "admin"
        org_id: "1"
        ds_type: "influxdb"
        url: "https://{{metric_store_ip}}:8086"
        database: "telegraf"
        time_interval: ">10s"
        tls_ca_cert: "/etc/ssl/certs/ca.pem"
    - service:
        name: "grafana-server"
        state: started

